cleanup: update test beforeAll
googleapis/java-container pull request #675
Opened 2022-02-07 22:55 UTC by ckim328

## Background
In this PR https://github.com/googleapis/java-container/issues/656 we saw that the quota for our clusters hit a max since tests were not cleaning up after themselves. Per Neenu's suggestion, we added a cleanup to the `beforeAll` to ensure that old clusters are deleted

2022-02-07 23:27 UTC, Shabirmean requested changes
Some minor comments and suggestions. Is there a way we can test? Are we creating clusters in the JDST project and re-triggering the CI on this PR?

2022-02-07 23:27 UTC, Shabirmean commented on google-cloud-container/src/test/java/com/google/cloud/container/v1/it/Util.java
> +  /** tear down any clusters that are older than 24 hours * */
Nit: `* */` -> `**/`

2022-02-07 23:27 UTC, Shabirmean commented on google-cloud-container/src/test/java/com/google/cloud/container/v1/it/Util.java
> +  public static boolean isCreatedBeforeThresholdTime(String timestamp) {
Can we make this method private?

2022-02-07 23:27 UTC, Shabirmean commented on google-cloud-container/src/test/java/com/google/cloud/container/v1/it/Util.java
> +        client.deleteCluster(projectId, zone, cluster.getName());
Is [this](https://cloud.google.com/java/docs/reference/google-cloud-container/latest/com.google.cloud.container.v1beta1.ClusterManagerClient#com_google_cloud_container_v1beta1_ClusterManagerClient_deleteCluster_java_lang_String_java_lang_String_java_lang_String_) an async operation? should we later check if the cluster properly got deleted before proceeding?

2022-02-07 23:37 UTC, Neenu1995 approved these changes

2022-02-07 23:37 UTC, Neenu1995 commented
LGTM. But address Shabir's comments before merging.

2022-02-08 14:07 UTC, ckim328 commented on google-cloud-container/src/test/java/com/google/cloud/container/v1/it/Util.java
> +  /** tear down any clusters that are older than 24 hours * */
eyes of an eagle!

2022-02-11 15:12 UTC, Shabirmean commented on google-cloud-container/src/test/java/com/google/cloud/container/v1/it/Util.java
> +  public static boolean isCreatedBeforeThresholdTime(String timestamp) {
I see it still being `public` in the latest commit. Do we want to stick to it. If it's not  used outside, Id change it to private.

2022-02-11 15:15 UTC, Shabirmean approved these changes
LGTM!

I see that the latest commits haven't still updated the code based on the comments. Maybe leave a feedback if you choose to not change them

2022-02-11 15:15 UTC, Shabirmean commented on google-cloud-container/src/test/java/com/google/cloud/container/v1/it/Util.java
> +        client.deleteCluster(projectId, zone, cluster.getName());
As discussed offline, this is not necessary to be handled in this PR

2022-02-11 17:23 UTC, merged